import path from 'node:path'
import { configHome } from './install-hooks.js'

/**
 * The OpenCode adapter (NotifAI-du1).
 *
 * OpenCode's extension point is a TypeScript/JavaScript plugin module, not a
 * command hook, so it needs a different adapter rather than a different path
 * through the existing one. What it is *not* is different logic: the generated
 * plugin shells out to the same `notifai hook <event>` commands Claude Code and
 * Codex invoke, and every decision — presence, the grace window, the reply
 * wait, retirement — stays in one place.
 *
 * The three joints map onto the same three events:
 *
 *   chat.message   -> user-prompt-submit   (the user is at the keyboard)
 *   session.idle   -> stop                 (the turn ended; escalate)
 *   permission.ask -> stop, decision read  (a blocked prompt to answer)
 *
 * `permission.ask` is the interesting one: its signature is
 * `(input, output) => Promise<void>` and the plugin *writes* the decision into
 * `output.status`, which is exactly the shape a remote answer needs. It is
 * async, so the plugin can block on the phone the way a command hook does.
 */

/** Marker line; also how an install from another checkout is recognised. */
export const OPENCODE_PLUGIN_MARKER = '// notifai managed opencode plugin'

/** Filename we own inside whichever plugins directory is being written. */
export const OPENCODE_PLUGIN_FILENAME = 'notifai.js'

export function opencodePluginDir(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return global
    ? path.join(configHome(env, 'OPENCODE_CONFIG_DIR', '.config/opencode'), 'plugins')
    : path.join(cwd, '.opencode', 'plugins')
}

export function opencodePluginPath(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return path.join(opencodePluginDir(global, cwd, env), OPENCODE_PLUGIN_FILENAME)
}

export interface OpencodePluginOptions {
  execPath: string
  scriptPath: string
  /** Must stay under OpenCode's own patience for a plugin hook. */
  timeoutSeconds: number
}

/**
 * The generated module.
 *
 * Written as a string rather than compiled from a source file because it has to
 * embed the absolute interpreter and script paths — a bare `notifai` on PATH
 * fails silently under a plugin host the same way it does under a hook shell.
 *
 * Everything it does is: build the hook envelope OpenCode's event gives it,
 * hand it to the CLI on stdin, and — for a permission request — read the
 * decision back off stdout. It deliberately fails open: any error, timeout or
 * unparseable answer leaves `output.status` untouched, so OpenCode falls
 * through to asking the user in the terminal. A notification adapter must never
 * be the reason a permission gets granted.
 */
export function opencodePluginSource(options: OpencodePluginOptions): string {
  const { execPath, scriptPath, timeoutSeconds } = options
  return `${OPENCODE_PLUGIN_MARKER}
// Generated by \`notifai hooks install --harness opencode\`. Edits are lost on
// the next install; change the CLI instead, which is where the logic lives.
import { spawn } from "node:child_process"

const EXEC = ${JSON.stringify(execPath)}
const SCRIPT = ${JSON.stringify(scriptPath)}
const TIMEOUT_MS = ${timeoutSeconds * 1000}

/**
 * Runs \`notifai hook <event>\`, feeding it the same JSON envelope the other
 * harnesses send. Resolves to stdout, or null if anything at all went wrong —
 * the caller treats null as "no opinion", which is what keeps this fail-open.
 */
function runHook(event, envelope) {
  return new Promise((resolve) => {
    let child
    try {
      child = spawn(EXEC, [SCRIPT, "hook", event, "--owner", "notifai"], {
        env: process.env,
        shell: false,
        stdio: ["pipe", "pipe", "pipe"],
      })
    } catch {
      resolve(null)
      return
    }

    let stdout = ""
    let settled = false
    const finish = (value) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    const timer = setTimeout(() => {
      child.kill("SIGTERM")
      finish(null)
    }, TIMEOUT_MS)

    child.stdout?.setEncoding("utf-8")
    child.stdout?.on("data", (chunk) => {
      stdout += chunk
    })
    // Hook stderr is diagnostics; OpenCode has nowhere to show it and it must
    // not be mistaken for the decision.
    child.stderr?.resume()
    child.on("error", () => finish(null))
    child.on("close", () => finish(stdout))

    try {
      child.stdin?.end(JSON.stringify(envelope))
    } catch {
      finish(null)
    }
  })
}

/** The Stop hook answers with a Claude-Code-shaped decision block or nothing. */
function decisionFrom(stdout) {
  if (typeof stdout !== "string" || stdout.trim() === "") return null
  try {
    const parsed = JSON.parse(stdout)
    if (parsed && parsed.decision === "block" && typeof parsed.reason === "string") {
      return parsed.reason
    }
  } catch {
    // Not a decision. Falling through to the terminal is the safe reading.
  }
  return null
}

export const NotifAIPlugin = async ({ directory }) => {
  const cwd = typeof directory === "string" && directory.length > 0 ? directory : process.cwd()

  return {
    /**
     * Presence. The user typing is the signal every harness shares, and it is
     * also what publishes the project -> session pointer \`notifai ask\` reads.
     */
    "chat.message": async (input) => {
      await runHook("user-prompt-submit", {
        session_id: input?.sessionID ?? input?.info?.sessionID,
        cwd,
        hook_event_name: "UserPromptSubmit",
      })
    },

    /** The turn ended: escalate a question registered with \`notifai ask\`. */
    "session.idle": async (input) => {
      await runHook("stop", {
        session_id: input?.sessionID,
        cwd,
        hook_event_name: "Stop",
      })
    },

    /**
     * A blocked permission prompt. The plugin writes the decision, so an answer
     * from the phone can allow or deny without the user touching the terminal.
     *
     * Only an explicit answer moves it. Anything else — no answer, a timeout, a
     * server that never replied — leaves \`output.status\` alone so OpenCode
     * asks the user itself. A notification adapter must never be the reason a
     * permission is granted.
     */
    "permission.ask": async (input, output) => {
      const stdout = await runHook("stop", {
        session_id: input?.sessionID,
        cwd,
        hook_event_name: "Stop",
        permission: {
          id: input?.id,
          type: input?.type,
          title: input?.title,
        },
      })
      const answer = decisionFrom(stdout)
      if (answer === null) return
      const normalized = answer.trim().toLowerCase()
      if (normalized.startsWith("allow") || normalized.startsWith("yes")) {
        output.status = "allow"
      } else if (normalized.startsWith("deny") || normalized.startsWith("no")) {
        output.status = "deny"
      }
    },

    /** Drop local session state; deliberately does no network work. */
    "session.deleted": async (input) => {
      await runHook("session-end", {
        session_id: input?.sessionID,
        cwd,
        hook_event_name: "SessionEnd",
      })
    },
  }
}
`
}

/** True when a plugin file on disk is one of ours, whoever installed it. */
export function isOurOpencodePlugin(contents: string): boolean {
  return contents.includes(OPENCODE_PLUGIN_MARKER)
}

/**
 * The interpreter and script a generated plugin will actually run.
 *
 * A plugin is a module rather than a command line, so which *build* it invokes
 * is not visible in the way it is for a settings-file handler — it is baked
 * into the two constants at the top. `doctor` needs it to answer the question
 * it exists to answer ("are two checkouts both installed?"), and without it
 * the plugin's own path stands in for the build and every OpenCode install
 * looks like a second one.
 *
 * Returns null for a plugin we did not generate, or one whose constants have
 * been edited out of recognisable shape.
 */
export function opencodePluginTarget(contents: string): { exec: string; script: string } | null {
  if (!isOurOpencodePlugin(contents)) return null
  const exec = /^const EXEC = (".*")$/m.exec(contents)?.[1]
  const script = /^const SCRIPT = (".*")$/m.exec(contents)?.[1]
  if (exec === undefined || script === undefined) return null
  try {
    return { exec: JSON.parse(exec) as string, script: JSON.parse(script) as string }
  } catch {
    return null
  }
}
