import path from 'node:path'
import { configHome } from './install-hooks.js'

/**
 * The OpenCode adapter (NotifAI-du1).
 *
 * OpenCode's extension point is a TypeScript/JavaScript plugin module, not a
 * command hook, so it needs a different adapter rather than a different path
 * through the existing one. What it is *not* is different logic: the generated
 * plugin shells out to the same `notifai hook <event>` commands Claude Code and
 * Codex invoke, and every decision — presence, the grace window, the reply
 * wait, retirement — stays in one place.
 *
 * The three lifecycle joints map onto the same three events. OpenCode exposes
 * `chat.message` as a direct hook, while session lifecycle notifications arrive
 * through its generic `event` hook:
 *
 *   chat.message   -> user-prompt-submit   (the user is at the keyboard)
 *   session.idle   -> stop                 (the turn ended; escalate)
 *   session.deleted -> session-end         (retire local session state)
 *
 * Permission prompts deliberately stay in OpenCode. The CLI question flow
 * only escalates questions explicitly registered with `notifai ask`.
 */

/** Marker line; also how an install from another checkout is recognised. */
export const OPENCODE_PLUGIN_MARKER = '// notifai managed opencode plugin'

/** Filename we own inside whichever plugins directory is being written. */
export const OPENCODE_PLUGIN_FILENAME = 'notifai.js'

/** Bump when an installed generated file must be rewritten to remain functional. */
const OPENCODE_ADAPTER_VERSION = 2

export function opencodePluginDir(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return global
    ? path.join(configHome(env, 'OPENCODE_CONFIG_DIR', '.config/opencode'), 'plugins')
    : path.join(cwd, '.opencode', 'plugins')
}

export function opencodePluginPath(
  global: boolean,
  cwd: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return path.join(opencodePluginDir(global, cwd, env), OPENCODE_PLUGIN_FILENAME)
}

export interface OpencodePluginOptions {
  execPath: string
  scriptPath: string
  /** Child-process lifetime; covers grace, reply wait, and teardown headroom. */
  timeoutSeconds: number
}

/**
 * The generated module.
 *
 * Written as a string rather than compiled from a source file because it has to
 * embed the absolute interpreter and script paths — a bare `notifai` on PATH
 * fails silently under a plugin host the same way it does under a hook shell.
 *
 * Everything it does is build the hook envelope OpenCode's event gives it and
 * hand that to the CLI on stdin. It deliberately fails open: an adapter error
 * never changes OpenCode's own behavior.
 */
export function opencodePluginSource(options: OpencodePluginOptions): string {
  const { execPath, scriptPath, timeoutSeconds } = options
  return `${OPENCODE_PLUGIN_MARKER}
// Generated by \`notifai hooks install --harness opencode\`. Edits are lost on
// the next install; change the CLI instead, which is where the logic lives.
import { spawn } from "node:child_process"

const EXEC = ${JSON.stringify(execPath)}
const SCRIPT = ${JSON.stringify(scriptPath)}
const TIMEOUT_MS = ${timeoutSeconds * 1000}
const ADAPTER_VERSION = ${OPENCODE_ADAPTER_VERSION}

/**
 * Runs \`notifai hook <event>\`, feeding it the same JSON envelope the other
 * harnesses send. Resolves to stdout, or null if anything at all went wrong.
 */
function runHook(event, envelope) {
  return new Promise((resolve) => {
    let child
    try {
      child = spawn(EXEC, [SCRIPT, "hook", event, "--owner", "notifai"], {
        env: process.env,
        shell: false,
        stdio: ["pipe", "pipe", "pipe"],
      })
    } catch {
      resolve(null)
      return
    }

    let stdout = ""
    let settled = false
    const finish = (value) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      resolve(value)
    }
    const timer = setTimeout(() => {
      child.kill("SIGTERM")
      finish(null)
    }, TIMEOUT_MS)

    child.stdout?.setEncoding("utf-8")
    child.stdout?.on("data", (chunk) => {
      stdout += chunk
    })
    // Hook stderr is diagnostics, not plugin output; discard it here.
    child.stderr?.resume()
    child.on("error", () => finish(null))
    child.on("close", () => finish(stdout))

    try {
      child.stdin?.end(JSON.stringify(envelope))
    } catch {
      finish(null)
    }
  })
}

export const NotifAIPlugin = async ({ directory }) => {
  const cwd = typeof directory === "string" && directory.length > 0 ? directory : process.cwd()

  return {
    /**
     * Presence. The user typing is the signal every harness shares, and it is
     * also what publishes the project -> session pointer \`notifai ask\` reads.
     */
    "chat.message": async (input) => {
      await runHook("user-prompt-submit", {
        session_id: input?.sessionID ?? input?.info?.sessionID,
        cwd,
        hook_event_name: "UserPromptSubmit",
      })
    },

    /** Session lifecycle events are delivered through OpenCode's event bus. */
    event: async ({ event }) => {
      if (event?.type === "session.idle") {
        await runHook("stop", {
          session_id: event?.properties?.sessionID,
          cwd,
          hook_event_name: "Stop",
        })
      } else if (event?.type === "session.deleted") {
        await runHook("session-end", {
          session_id: event?.properties?.info?.id,
          cwd,
          hook_event_name: "SessionEnd",
        })
      }
    },
  }
}
`
}

/** True when a plugin file on disk is one of ours, whoever installed it. */
export function isOurOpencodePlugin(contents: string): boolean {
  return contents.includes(OPENCODE_PLUGIN_MARKER)
}

/**
 * The interpreter and script a generated plugin will actually run.
 *
 * A plugin is a module rather than a command line, so which *build* it invokes
 * is not visible in the way it is for a settings-file handler — it is baked
 * into the two constants at the top. `doctor` needs it to answer the question
 * it exists to answer ("are two checkouts both installed?"), and without it
 * the plugin's own path stands in for the build and every OpenCode install
 * looks like a second one.
 *
 * Returns null for a plugin we did not generate, or one whose constants have
 * been edited out of recognisable shape.
 */
export function opencodePluginTarget(
  contents: string,
): { exec: string; script: string; current: boolean } | null {
  if (!isOurOpencodePlugin(contents)) return null
  const exec = /^const EXEC = (".*")$/m.exec(contents)?.[1]
  const script = /^const SCRIPT = (".*")$/m.exec(contents)?.[1]
  const version = Number(/^const ADAPTER_VERSION = (\d+)$/m.exec(contents)?.[1] ?? 1)
  if (exec === undefined || script === undefined) return null
  try {
    return {
      exec: JSON.parse(exec) as string,
      script: JSON.parse(script) as string,
      current: version === OPENCODE_ADAPTER_VERSION,
    }
  } catch {
    return null
  }
}
